### ISSUE TITLE
spiking learning rule

### ISSUE THREAD

**Issue by tcstewar** [tcstewar/2015-Embodied_Benchmarks#27]
Chris commented that we should say something about this learning rule also working fine with spiking neurons.  Here's my attempt at that:

```
Importantly, it functions well with spiking neuron models as
well as non-spiking ones.  For spiking neurons, we consider $A$ to be the
instantaneous measure of the output of a neuron (i.e. whether or not it is currently outputing a spike),
filtered through a low-pass filter.  Further discussion of this sort of learning
rule and comparison to biological spiking neurons is given by [ref?].
```

What would be a good citation for that?  Trevor's thesis?

**Comment by celiasmith** [comment]
I'd probably cite:

Trevor Bekolay, Carter Kolbeck, and Chris Eliasmith. Simultaneous unsupervised and supervised learning of cognitive functions in biologically plausible spiking neural networks. In 35th Annual Conference of the Cognitive Science Society, 169-174. Cognitive Science Society, 2013.

and (optionally)

Trevor Bekolay. Learning in large-scale spiking neural networks. Master's thesis, University of Waterloo, Waterloo, ON, 09/2011 2011. URL: http://uwspace.uwaterloo.ca/handle/10012/6195.

**Comment by tcstewar** [comment]
Thanks!
