### ISSUE TITLE
Talk about the NEF-assumptions a bit

### ISSUE THREAD

**Issue by tcstewar** [tcstewar/2015-Embodied_Benchmarks#28]
The whole approach in the paper is very NEFish, but we don't really make that explicit.  Heck, right now there isn't even a citation about it.  Chris raises this point a bit in his pdf comment:

>  (Also, I think there might be a lot of NEF type assumptions in this (and the previous few para) discussions that won't be shared by readers (like having error signals that you can interpret in high-d spaces easily, dealing with dynamics, spikes, having a learning rule that does those things, etc... not sure exactly what to do about that, but might be worth thinking about on a rewrite. 

I'm mostly just posting this issue so I don't forget about it.  There at least needs to be a specific citation to the 2003 book somewhere....

**Comment by celiasmith** [comment]
In a way, I like that the connection is minimal, so the paper stands clearly on it's own ... but some pointer is probably appropriate in case of confusion

**Comment by tcstewar** [comment]
Done:

```
This type of neural modelling forms the foundation of Eliasmith and Anderson (2003)’s Neural
Engineering Framework, which has shown that spiking and non-spiking neurons can be used in this manner
to implement a wide variety of computations (e.g., Stewart and Eliasmith 2014).
```
